# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('obsid', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date observed')),
                ('trig', models.CharField(max_length=200)),
                ('inst', models.CharField(max_length=200)),
                ('lev0', models.CharField(max_length=200)),
                ('lev1', models.CharField(max_length=200)),
                ('prev', models.CharField(max_length=200)),
            ],
        ),
    ]
