# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciencedata',
            name='lat',
            field=models.FloatField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='sciencedata',
            name='lon',
            field=models.FloatField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='sciencedata',
            name='obsid',
            field=models.FloatField(verbose_name=0),
        ),
    ]
