# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsimData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trig', models.CharField(max_length=200)),
                ('lev1', models.CharField(max_length=200)),
                ('lev2', models.CharField(max_length=200)),
                ('inst', models.CharField(max_length=200)),
                ('prev', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('obsid', models.FloatField()),
                ('obs_date', models.DateTimeField(verbose_name='date observed')),
            ],
        ),
    ]
