from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField
import datetime
from django.contrib import admin
from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField
import datetime
from django.contrib import admin




class MXGSBGODAU3FullHousekeepingTM(models.Model):
    packet_length                   = models.IntegerField('Packet length')
    utc_year                        = models.IntegerField('UTC year')
    utc_msec                        = models.IntegerField('UTC msec')
    utc_seconds                     = models.IntegerField('UTC seconds')
    tcp_count_dpu                   = models.IntegerField()
    acquisition_start_time_current  = models.IntegerField()
    grey_mode_data_reduc_factor     = models.IntegerField()
    dau_bgo_1_ratemeter             = models.IntegerField()
    dau_bgo_1_tmon_chan_1           = models.IntegerField()
    dau_bgo_1_tmon_chan_2           = models.IntegerField()
    dau_bgo_1_internal_tmon_chan_1  = models.IntegerField()
    dau_bgo_1_internal_tmon_chan_2  = models.IntegerField()
    dau_bgo_1_internal_tmon_chan_3  = models.IntegerField()
    dau_bgo_1_tmon_ref_voltage      = models.IntegerField()
    dau_rcu_master_cr0_sdctest = models.BooleanField()
    dau_rcu_master_cr0_mrst_master_reset = models.BooleanField()
    dau_rcu_master_cr1_valley_en2 = models.BooleanField()
    dau_rcu_master_cr1_offset_en2 = models.BooleanField()
    dau_rcu_master_cr1_valley_en1 = models.BooleanField()
    dau_rcu_master_cr1_offset_en1 = models.BooleanField()
    dau_rcu_master_cr1_valley_en0 = models.BooleanField()
    dau_rcu_master_cr1_offset_en0 = models.BooleanField()
    dau_rcu_master_cr2_flagbit_test = models.BooleanField()
    dau_rcu_master_cr2_timetag_test = models.BooleanField()
    dau_rcu_master_cr2_address_test = models.BooleanField()
    dau_rcu_master_cr2_energy_test = models.BooleanField()
    dau_rcu_master_cr3_noblink_inhibit_led = models.BooleanField()
    dau_rcu_master_cr3_debugsel = models.IntegerField()
    dau_rcu_master_sr0_firmware_version_low_byte = models.IntegerField()
    dau_rcu_master_sr0_firmware_version_high_byte = models.IntegerField()
    dau_pmt_if_1_cr0_decf = models.IntegerField()
    dau_pmt_if_1_cr1_valtrig = models.IntegerField()
    dau_pmt_if_1_cr2_pptrig = models.IntegerField()
    dau_pmt_if_1_cr3_ade_enable_adc = models.BooleanField()
    dau_pmt_if_1_cr3_smp_enable_con_sample = models.BooleanField()
    dau_pmt_if_1_cr3_tce_enable_tail_cancel = models.BooleanField()
    dau_pmt_if_1_cr3_tsmp_enable_trig_sample = models.BooleanField()
    dau_pmt_if_1_cr3_offlockt = models.IntegerField()
    dau_pmt_if_1_cr4_tail_decay_1 = models.IntegerField()
    dau_pmt_if_1_cr5_tail_decay_2 = models.IntegerField()
    dau_pmt_if_1_cr6_tail_gain_1 = models.IntegerField()
    dau_pmt_if_1_cr7_tail_gain_2 = models.IntegerField()
    dau_pmt_if_1_sr0_offvall = models.IntegerField()
    dau_pmt_if_1_sr1_offvalh = models.IntegerField()
    dau_pmt_if_1_sr2_tovrthrl = models.IntegerField()
    dau_pmt_if_1_sr2_tovrthrh = models.IntegerField()

    dau_pmt_if_2_cr0_decf = models.IntegerField()
    dau_pmt_if_2_cr1_valtrig = models.IntegerField()
    dau_pmt_if_2_cr2_pptrig = models.IntegerField()
    dau_pmt_if_2_cr3_ade_enable_adc = models.BooleanField()
    dau_pmt_if_2_cr3_smp_enable_con_sample = models.BooleanField()
    dau_pmt_if_2_cr3_tce_enable_tail_cancel = models.BooleanField()
    dau_pmt_if_2_cr3_tsmp_enable_trig_sample = models.BooleanField()
    dau_pmt_if_2_cr3_offlockt = models.IntegerField()
    dau_pmt_if_2_cr4_tail_decay_1 = models.IntegerField()
    dau_pmt_if_2_cr5_tail_decay_2 = models.IntegerField()
    dau_pmt_if_2_cr6_tail_gain_1 = models.IntegerField()
    dau_pmt_if_2_cr7_tail_gain_2 = models.IntegerField()
    dau_pmt_if_2_sr0_offvall = models.IntegerField()
    dau_pmt_if_2_sr1_offvalh = models.IntegerField()
    dau_pmt_if_2_sr2_tovrthrl = models.IntegerField()
    dau_pmt_if_2_sr2_tovrthrh = models.IntegerField()

    dau_pmt_if_3_cr0_decf = models.IntegerField()
    dau_pmt_if_3_cr1_valtrig = models.IntegerField()
    dau_pmt_if_3_cr2_pptrig = models.IntegerField()
    dau_pmt_if_3_cr3_ade_enable_adc = models.BooleanField()
    dau_pmt_if_3_cr3_smp_enable_con_sample = models.BooleanField()
    dau_pmt_if_3_cr3_tce_enable_tail_cancel = models.BooleanField()
    dau_pmt_if_3_cr3_tsmp_enable_trig_sample = models.BooleanField()
    dau_pmt_if_3_cr3_offlockt = models.IntegerField()
    dau_pmt_if_3_cr4_tail_decay_1 = models.IntegerField()
    dau_pmt_if_3_cr5_tail_decay_2 = models.IntegerField()
    dau_pmt_if_3_cr6_tail_gain_1 = models.IntegerField()
    dau_pmt_if_3_cr7_tail_gain_2 = models.IntegerField()
    dau_pmt_if_3_sr0_offvall = models.IntegerField()
    dau_pmt_if_3_sr1_offvalh = models.IntegerField()
    dau_pmt_if_3_sr2_tovrthrl = models.IntegerField()
    dau_pmt_if_3_sr2_tovrthrh = models.IntegerField()

    dau_tmon_cr0_tupdate = models.BooleanField()
    dau_tmon_cr1_tmon_enable = models.BooleanField()
    dau_tmon_cr2_clock_division_factor = models.IntegerField()
    dau_tmon_sr1_sampled_temp_val_0_lsb = models.IntegerField()
    dau_tmon_sr2_sampled_temp_val_0_msb = models.IntegerField()
    dau_tmon_sr3_sampled_temp_val_1_lsb = models.IntegerField()
    dau_tmon_sr4_sampled_temp_val_1_msb = models.IntegerField()
    dau_tmon_sr5_sampled_temp_val_2_lsb = models.IntegerField()
    dau_tmon_sr6_sampled_temp_val_2_msb = models.IntegerField()
    dau_tmon_sr7_sampled_ref_voltage_msb = models.IntegerField()
    dau_bcm_sr0_total_hit_counter_low_byte = models.IntegerField()
    dau_bcm_sr0_total_hit_counter_middle_byte = models.IntegerField()
    dau_bcm_sr0_total_hit_counter_high_byte = models.IntegerField()
    dau_bcm_cr_spectral_boundary_low = models.IntegerField()
    dau_bcm_cr_spectral_boundary_1 = models.IntegerField()
    dau_bcm_cr_spectral_boundary_2 = models.IntegerField()
    dau_bcm_cr_spectral_boundary_3 = models.IntegerField()
    dau_bcm_cr_spectral_boundary_4 = models.IntegerField()
    dau_bcm_cr_spectral_boundary_5 = models.IntegerField()
    dau_bcm_cr_spectral_boundary_6 = models.IntegerField()
    dau_bcm_cr_spectral_boundary_7 = models.IntegerField()
    dau_bcm_cr_spectral_boundary_8 = models.IntegerField()
    dau_bcm_cr_spectral_boundary_9 = models.IntegerField()
    dau_bcm_cr_spectral_boundary_high = models.IntegerField()
    dau_bcm_cr_temporal_bin_size = models.IntegerField()


