from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField
import datetime
from django.contrib import admin

class MXGSTGFObservation(models.Model):
    observation_id                  =models.IntegerField('Observation ID')
    utc_year                        =models.IntegerField('UTC year')
    utc_seconds                     =models.IntegerField('UTC seconds')
    utc_msec                        =models.IntegerField('UTC msec')
    tcp_count_dhpu                  =models.IntegerField()
    tcp_count_dpu                   =models.IntegerField()
    dpu_count                       =models.IntegerField()
    dpu_count_prereset              =models.IntegerField()
    dau_bgo_1_int_tmon_chan1        =models.IntegerField()
    dau_bgo_1_int_tmon_chan2        =models.IntegerField()
    dau_bgo_1_int_tmon_chan3        =models.IntegerField()
    dau_bgo_1_int_tmon_chan4        =models.IntegerField()
    dau_bgo_2_int_tmon_chan1        =models.IntegerField()
    dau_bgo_2_int_tmon_chan2        =models.IntegerField()
    dau_bgo_2_int_tmon_chan3        =models.IntegerField()
    dau_bgo_2_int_tmon_chan4        =models.IntegerField()
    dau_bgo_3_int_tmon_chan1        =models.IntegerField()
    dau_bgo_3_int_tmon_chan2        =models.IntegerField()
    dau_bgo_3_int_tmon_chan3        =models.IntegerField()
    dau_bgo_3_int_tmon_chan4        =models.IntegerField()
    dau_bgo_4_int_tmon_chan1        =models.IntegerField()
    dau_bgo_4_int_tmon_chan2        =models.IntegerField()
    dau_bgo_4_int_tmon_chan3        =models.IntegerField()
    dau_bgo_4_int_tmon_chan4        =models.IntegerField()
    led_short_win_lr_pulse_height   =models.IntegerField()
    led_short_win_upr_pulse_height  =models.IntegerField()
    led_long_win_lr_pulse_height    =models.IntegerField()
    led_long_win_upr_pulse_height   =models.IntegerField()
    hed_short_win_lr_pulse_height   =models.IntegerField()
    hed_short_win_upr_pulse_height  =models.IntegerField()
    hed_long_win_lr_pulse_height    =models.IntegerField()
    hed_long_win_upr_pulse_height   =models.IntegerField()
    led_short_win_anticoin_time     =models.IntegerField()
    led_long_win_anticoin_time      =models.IntegerField()
    hed_short_win_anticoin_time     =models.IntegerField()
    hed_long_win_anticoin_time      =models.IntegerField()
    led_short_win_flag1             =models.BooleanField()
    led_short_win_flag2             =models.BooleanField()
    led_short_win_flag3             =models.BooleanField()
    led_long_win_flag               =models.BooleanField()
    hed_short_win_flag1             =models.BooleanField()
    hed_short_win_flag2             =models.BooleanField()
    hed_short_win_flag3             =models.BooleanField()
    hed_long_win_flag               =models.BooleanField()
    trig_mmia_enabled               =models.BooleanField()
    trig_mmia_recd                  =models.BooleanField()
    led_short_win_dur_1             =models.IntegerField()
    led_short_win_dur_2             =models.IntegerField()
    led_short_win_dur_3             =models.IntegerField()
    led_long_win_dur                =models.IntegerField()
    hed_short_win_dur_1             =models.IntegerField()
    hed_short_win_dur_2             =models.IntegerField()
    hed_short_win_dur_3             =models.IntegerField()
    hed_long_win_dur                =models.IntegerField()
    led_short_win_thresh_1          =models.IntegerField()
    led_short_win_thresh_2          =models.IntegerField()
    led_short_win_thresh_3          =models.IntegerField()
    led_long_win_thresh             =models.IntegerField()
    hed_short_win_thresh_1          =models.IntegerField()
    hed_short_win_thresh_2          =models.IntegerField()
    hed_short_win_thresh_3          =models.IntegerField()
    hed_long_win_thresh             =models.IntegerField()
    mxgs_trig_count                 =models.BigIntegerField()
    mxgs_trig_tcp_count             =models.IntegerField()
    mxgs_trig_dpu_count             =models.IntegerField()
    num_counts                      =models.IntegerField()
    detector_counts                 =models.FileField()
    
 
# Background Observation
